theme: jekyll-theme-minimal
title: [Five Prayers Android]
description: [A set of muslim tools]
logo: ic_launcher.png
github:
    repository_url: https://github.com/Five-Prayers/five-prayers-android
    is_user_page: false
    
