package com.hbouzidi.fiveprayers.utils;

import com.hbouzidi.fiveprayers.R;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public class FontBySurahNumber {

    private static final Map<Integer, SurahFontReference> FONT_ID_BY_SURAH_NUMBER = createMap();

    private FontBySurahNumber() {
    }

    private static Map<Integer, SurahFontReference> createMap() {
        Map<Integer, SurahFontReference> result = new HashMap<>();

        result.put(1, new SurahFontReference(R.font.mcs_gf1, "\u0030", "\u0031"));            //Al-Fatihah (The Opening)
        result.put(2, new SurahFontReference(R.font.mcs_gf1, "\u0032", "\u0033"));            //Al-Baqarah (The Cow)
        result.put(3, new SurahFontReference(R.font.mcs_gf1, "\u0034", "\u0035"));            //Al-'Imran (The Family of Amran)
        result.put(4, new SurahFontReference(R.font.mcs_gf1, "\u0036", "\u0037"));            //An-Nisa' (The Women)
        result.put(5, new SurahFontReference(R.font.mcs_gf1, "\u0038", "\u0039"));            //Al-Ma'idah (The Food)
        result.put(6, new SurahFontReference(R.font.mcs_gf1, "\u0041", "\u0042"));            //Al-An'am (The Cattle)
        result.put(7, new SurahFontReference(R.font.mcs_gf1, "\u0043", "\u0044"));            //Al-A'raf (The Elevated Places)
        result.put(8, new SurahFontReference(R.font.mcs_gf1, "\u0045", "\u0046"));            //Al-Anfal (Voluntary Gifts)
        result.put(9, new SurahFontReference(R.font.mcs_gf1, "\u0047", "\u0048"));            //Al-Bara'at / At-Taubah(The Immunity)
        result.put(10, new SurahFontReference(R.font.mcs_gf1, "\u0049", "\u004A"));           //Yunus (Jonah)
        result.put(11, new SurahFontReference(R.font.mcs_gf1, "\u004B", "\u004C"));           //Hud (Hud)
        result.put(12, new SurahFontReference(R.font.mcs_gf1, "\u004D", "\u004E"));           //Yusuf (Joseph)
        result.put(13, new SurahFontReference(R.font.mcs_gf1, "\u004F", "\u0050"));           //Ar-Ra'd (The Thunder)
        result.put(14, new SurahFontReference(R.font.mcs_gf1, "\u0051", "\u0052"));           //Ibrahim (Abraham)
        result.put(15, new SurahFontReference(R.font.mcs_gf1, "\u0053", "\u0054"));           //Al-Hijr (The Rock)
        result.put(16, new SurahFontReference(R.font.mcs_gf1, "\u0055", "\u0056"));           //An-Nahl (The Bee)
        result.put(17, new SurahFontReference(R.font.mcs_gf1, "\u0057", "\u0058"));           //Bani Isra'il (The Israelites)
        result.put(18, new SurahFontReference(R.font.mcs_gf1, "\u0059", "\u005A"));           //Al-Kahf (The Cave)
        result.put(19, new SurahFontReference(R.font.mcs_gf1, "\u0061", "\u0062"));           //Maryam (Mary)
        result.put(20, new SurahFontReference(R.font.mcs_gf1, "\u0063", "\u0064"));           //Ta Ha (Ta Ha)
        result.put(21, new SurahFontReference(R.font.mcs_gf1, "\u0065", "\u0066"));           //Al-Anbiya' (The Prophets)
        result.put(22, new SurahFontReference(R.font.mcs_gf1, "\u0067", "\u0068"));           //Al-Hajj (The Pilgrimage)
        result.put(23, new SurahFontReference(R.font.mcs_gf1, "\u0069", "\u006A"));           //Al-Mu'minun (The Believers)
        result.put(24, new SurahFontReference(R.font.mcs_gf1, "\u006B", "\u006B"));           //An-Nur (The Light)
        result.put(25, new SurahFontReference(R.font.mcs_gf1, "\u006C", "\u006D"));           //Al-Furqan (The Discrimination)
        result.put(26, new SurahFontReference(R.font.mcs_gf1, "\u006E", "\u006F"));           //Ash-Shu'ara' (The Poets)
        result.put(27, new SurahFontReference(R.font.mcs_gf1, "\u0070", "\u0071"));           //An-Naml (The Naml)
        result.put(28, new SurahFontReference(R.font.mcs_gf1, "\u0072", "\u0073"));           //Al-Qasas (The Narrative)
        result.put(29, new SurahFontReference(R.font.mcs_gf1, "\u0074", "\u0075"));           //Al-'Ankabut (The Spider)
        result.put(30, new SurahFontReference(R.font.mcs_gf1, "\u0076", "\u0077"));           //Ar-Rum (The Romans)
        result.put(31, new SurahFontReference(R.font.mcs_gf1, "\u0078", "\u0079"));           //Luqman (Luqman)
        result.put(32, new SurahFontReference(R.font.mcs_gf2, "\u0030", "\u0031"));           //As-Sajdah (The Adoration)
        result.put(33, new SurahFontReference(R.font.mcs_gf2, "\u0032", "\u0033"));           //Al-Ahzab (The Allies)
        result.put(34, new SurahFontReference(R.font.mcs_gf2, "\u0034", "\u0035"));           //Al-Saba' (The Saba')
        result.put(35, new SurahFontReference(R.font.mcs_gf2, "\u0036", "\u0037"));           //Al-Fatir (The Originator)
        result.put(36, new SurahFontReference(R.font.mcs_gf2, "\u0038", "\u0038"));           //Ya Sin (Ya Sin)
        result.put(37, new SurahFontReference(R.font.mcs_gf2, "\u0041", "\u0042"));           //As-Saffat (Those Ranging in Ranks)
        result.put(38, new SurahFontReference(R.font.mcs_gf2, "\u0043", "\u0044"));           //Sad (Sad)
        result.put(39, new SurahFontReference(R.font.mcs_gf2, "\u0045", "\u0046"));           //Az-Zumar (The Companies)
        result.put(40, new SurahFontReference(R.font.mcs_gf2, "\u0047", "\u0048"));           //Al-Mu'min (The Believer)
        result.put(41, new SurahFontReference(R.font.mcs_gf2, "\u0049", "\u004A"));           //Ha Mim (Ha Mim)
        result.put(42, new SurahFontReference(R.font.mcs_gf2, "\u004B", "\u004C"));           //Ash-Shura (Counsel)
        result.put(43, new SurahFontReference(R.font.mcs_gf2, "\u004D", "\u004E"));           //Az-Zukhruf (Gold)
        result.put(44, new SurahFontReference(R.font.mcs_gf2, "\u004F", "\u0050"));           //Ad-Dukhan (The Drought)
        result.put(45, new SurahFontReference(R.font.mcs_gf2, "\u0051", "\u0052"));           //Al-Jathiyah (The Kneeling)
        result.put(46, new SurahFontReference(R.font.mcs_gf2, "\u0053", "\u0054"));           //Al-Ahqaf (The Sandhills)
        result.put(47, new SurahFontReference(R.font.mcs_gf2, "\u0055", "\u0056"));           //Muhammad (Muhammad)
        result.put(48, new SurahFontReference(R.font.mcs_gf2, "\u0057", "\u0058"));           //Al-Fath (The Victory)
        result.put(49, new SurahFontReference(R.font.mcs_gf2, "\u0059", "\u005A"));           //Al-Hujurat (The Apartments)
        result.put(50, new SurahFontReference(R.font.mcs_gf2, "\u0061", "\u0062"));           //Qaf (Qaf)
        result.put(51, new SurahFontReference(R.font.mcs_gf2, "\u0063", "\u0064"));           //Ad-Dhariyat (The Scatterers)
        result.put(52, new SurahFontReference(R.font.mcs_gf2, "\u0065", "\u0066"));           //At-Tur (The Mountain)
        result.put(53, new SurahFontReference(R.font.mcs_gf2, "\u0067", "\u0068"));           //An-Najm (The Star)
        result.put(54, new SurahFontReference(R.font.mcs_gf2, "\u0069", "\u006A"));           //Al-Qamar (The Moon)
        result.put(55, new SurahFontReference(R.font.mcs_gf2, "\u006B", "\u006C"));           //Ar-Rahman (The Beneficent)
        result.put(56, new SurahFontReference(R.font.mcs_gf2, "\u006D", "\u006E"));           //Al-Waqi'ah (The Event)
        result.put(57, new SurahFontReference(R.font.mcs_gf2, "\u006F", "\u0070"));           //Al-Hadid (Iron)
        result.put(58, new SurahFontReference(R.font.mcs_gf2, "\u0071", "\u0072"));           //Al-Mujadilah (The Pleading Woman)
        result.put(59, new SurahFontReference(R.font.mcs_gf2, "\u0073", "\u0074"));           //Al-Hashr (The Banishment)
        result.put(60, new SurahFontReference(R.font.mcs_gf2, "\u0075", "\u0076"));           //Al-Mumtahanah (The Woman who is Examined)
        result.put(61, new SurahFontReference(R.font.mcs_gf2, "\u0077", "\u0078"));           //As-Saff (The Ranks)
        result.put(62, new SurahFontReference(R.font.mcs_gf2, "\u0079", "\u007A"));           //Al-Jumu'ah (The Congregation)
        result.put(63, new SurahFontReference(R.font.mcs_gf3, "\u0030", "\u0031"));           //Al-Munafiqun (The Hypocrites)
        result.put(64, new SurahFontReference(R.font.mcs_gf3, "\u0032", "\u0033"));           //At-Taghabun (The Manifestation of Losses)
        result.put(65, new SurahFontReference(R.font.mcs_gf3, "\u0034", "\u0035"));           //At-Talaq (Divorce)
        result.put(66, new SurahFontReference(R.font.mcs_gf3, "\u0036", "\u0037"));           //At-Tahrim (The Prohibition)
        result.put(67, new SurahFontReference(R.font.mcs_gf3, "\u0038", "\u0039"));           //Al-Mulk (The Kingdom)
        result.put(68, new SurahFontReference(R.font.mcs_gf3, "\u0041", "\u0042"));           //Al-Qalam (The Pen)
        result.put(69, new SurahFontReference(R.font.mcs_gf3, "\u0043", "\u0044"));           //Al-Haqqah (The Sure Truth)
        result.put(70, new SurahFontReference(R.font.mcs_gf3, "\u0045", "\u0046"));           //Al-Ma'arij (The Ways of Ascent)
        result.put(71, new SurahFontReference(R.font.mcs_gf3, "\u0047", "\u0048"));           //Nuh (Noah)
        result.put(72, new SurahFontReference(R.font.mcs_gf3, "\u0049", "\u004A"));           //Al-Jinn (The Jinn)
        result.put(73, new SurahFontReference(R.font.mcs_gf3, "\u004B", "\u004C"));           //Al-Muzzammil (The One Covering Himself)
        result.put(74, new SurahFontReference(R.font.mcs_gf3, "\u004D", "\u004E"));           //Al-Muddaththir (The One Wrapping Himself Up)
        result.put(75, new SurahFontReference(R.font.mcs_gf3, "\u004F", "\u0050"));           //Al-Qiyamah (The Resurrection)
        result.put(76, new SurahFontReference(R.font.mcs_gf3, "\u0051", "\u0052"));           //Al-Insan (The Man)
        result.put(77, new SurahFontReference(R.font.mcs_gf3, "\u0053", "\u0054"));           //Al-Mursalat (Those Sent Forth)
        result.put(78, new SurahFontReference(R.font.mcs_gf3, "\u0055", "\u0056"));           //An-Naba' (The Announcement)
        result.put(79, new SurahFontReference(R.font.mcs_gf3, "\u0057", "\u0058"));           //An-Nazi'at (Those Who Yearn)
        result.put(80, new SurahFontReference(R.font.mcs_gf3, "\u0059", "\u005A"));           //'Abasa (He Frowned)
        result.put(81, new SurahFontReference(R.font.mcs_gf3, "\u0061", "\u0062"));           //At-Takwir (The Folding Up)
        result.put(82, new SurahFontReference(R.font.mcs_gf3, "\u0063", "\u0064"));           //Al-Infitar (The Cleaving)
        result.put(83, new SurahFontReference(R.font.mcs_gf3, "\u0065", "\u0066"));           //At-Tatfif (Default in Duty)
        result.put(84, new SurahFontReference(R.font.mcs_gf3, "\u0067", "\u0068"));           //Al-Inshiqaq (The Bursting Asunder)
        result.put(85, new SurahFontReference(R.font.mcs_gf3, "\u0069", "\u006A"));           //Al-Buruj (The Stars)
        result.put(86, new SurahFontReference(R.font.mcs_gf3, "\u006B", "\u006C"));           //At-Tariq (The Comer by Night)
        result.put(87, new SurahFontReference(R.font.mcs_gf3, "\u006D", "\u006E"));           //Al-A'la (The Most High)
        result.put(88, new SurahFontReference(R.font.mcs_gf3, "\u006F", "\u0070"));           //Al-Ghashiyah (The Overwhelming Event)
        result.put(89, new SurahFontReference(R.font.mcs_gf3, "\u0071", "\u0072"));           //Al-Fajr (The Daybreak)
        result.put(90, new SurahFontReference(R.font.mcs_gf3, "\u0073", "\u0074"));           //Al-Balad (The City)
        result.put(91, new SurahFontReference(R.font.mcs_gf3, "\u0075", "\u0076"));           //Ash-Shams (The Sun)
        result.put(92, new SurahFontReference(R.font.mcs_gf3, "\u0077", "\u0078"));           //Al-Lail (The Night)
        result.put(93, new SurahFontReference(R.font.mcs_gf3, "\u0079", "\u007A"));           //Ad-Duha (The Brightness of the Day)
        result.put(94, new SurahFontReference(R.font.mcs_gf4, "\u0030", "\u0031"));           //Al-Inshirah (The Expansion)
        result.put(95, new SurahFontReference(R.font.mcs_gf4, "\u0032", "\u0033"));           //At-Tin (The Fig)
        result.put(96, new SurahFontReference(R.font.mcs_gf4, "\u0034", "\u0035"));           //Al-'Alaq (The Clot)
        result.put(97, new SurahFontReference(R.font.mcs_gf4, "\u0036", "\u0037"));           //Al-Qadr (The Majesty)
        result.put(98, new SurahFontReference(R.font.mcs_gf4, "\u0038", "\u0039"));          //Al-Bayyinah (The Clear Evidence)
        result.put(99, new SurahFontReference(R.font.mcs_gf4, "\u0041", "\u0042"));          //Al-Zilzal (The Shaking)
        result.put(100, new SurahFontReference(R.font.mcs_gf4, "\u0043", "\u0044"));          //Al-'Adiyat (The Assaulters)
        result.put(101, new SurahFontReference(R.font.mcs_gf4, "\u0045", "\u0046"));          //Al-Qari'ah (The Calamity)
        result.put(102, new SurahFontReference(R.font.mcs_gf4, "\u0047", "\u0048"));          //At-Takathur (The Abundance of Wealth)
        result.put(103, new SurahFontReference(R.font.mcs_gf4, "\u0049", "\u004A"));          //Al-'Asr (The Time)
        result.put(104, new SurahFontReference(R.font.mcs_gf4, "\u004B", "\u004C"));          //Al-Humazah (The Slanderer)
        result.put(105, new SurahFontReference(R.font.mcs_gf4, "\u004D", "\u004E"));          //Al-Fil (The Elephant)
        result.put(106, new SurahFontReference(R.font.mcs_gf4, "\u004F", "\u0050"));          //Al-Quraish (The Quraish)
        result.put(107, new SurahFontReference(R.font.mcs_gf4, "\u0051", "\u0052"));          //Al-Ma'un (Acts of Kindness)
        result.put(108, new SurahFontReference(R.font.mcs_gf4, "\u0053", "\u0054"));          //Al-Kauthar (The Abundance of Good)
        result.put(109, new SurahFontReference(R.font.mcs_gf4, "\u0055", "\u0056"));          //Al-Kafirun (The Disbelievers)
        result.put(110, new SurahFontReference(R.font.mcs_gf4, "\u0057", "\u0058"));          //An-Nasr (The Help)
        result.put(111, new SurahFontReference(R.font.mcs_gf4, "\u0059", "\u005A"));          //Al-Lahab (The Flame)
        result.put(112, new SurahFontReference(R.font.mcs_gf4, "\u0061", "\u0062"));          //Al-Ikhlas (The Unity)
        result.put(113, new SurahFontReference(R.font.mcs_gf4, "\u0063", "\u0064"));          //Al-Falaq (The Dawn)
        result.put(114, new SurahFontReference(R.font.mcs_gf4, "\u0065", "\u0066"));          //An-Nas (The Men)

        return Collections.unmodifiableMap(result);
    }

    public static SurahFontReference getSurahFontReference(int surahNumber) {
        return FONT_ID_BY_SURAH_NUMBER.get(surahNumber);
    }
}
